# Generated by Django 4.2.7 on 2023-11-16 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oblog', '0002_post_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo_url',
            field=models.CharField(default='post', max_length=255),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comentarios', to='oblog.post')),
            ],
        ),
    ]
