# Generated by Django 4.2.7 on 2023-11-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oblog', '0004_category_rename_body_comment_corpo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categoria',
        ),
        migrations.AddField(
            model_name='post',
            name='categorias',
            field=models.ManyToManyField(to='oblog.category'),
        ),
    ]
